grupo5:
  storage:
    storage-type: ${STORAGE_TYPE:S3}
    s3:
      id-access-key: ${ID_ACCESS_KEY:}
      secret-access-key: ${SECRET_ACCESS_KEY:}
      bucket: ${BUCKET:}
      region: ${REGION:}
      pictures-path: ${PICTURES_PATH:}

spring:
  application:
    name: catalog-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:catalog-db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345678}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: POSTGRESQL