on: [push, pull_request]

jobs:
  catalog-db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: catalog-db
        ports:
          - 5432:5432

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          count=0
          max_retries=30
          until nc -z localhost 5432 || [ $count -eq $max_retries ]; do
            count=$((count + 1))
            echo "Waiting for PostgreSQL to be ready... Attempt $count of $max_retries"
            sleep 5
          done
          if [ $count -eq $max_retries ]; then
            echo "PostgreSQL did not start in time."
            exit 1
          fi
          echo "PostgreSQL is ready!"

  build:
    needs: catalog-db
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/setup-gradle@v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/dependency-submission@v3.1.0